/* =========================================================
   Viveros Jazmín — Product catalogue + translations
   Edit this file to add/remove products or change UI strings.
   Languages: es (Castellano), va (Valencià)
   ========================================================= */

const SITE_INFO = {
  name: "Viveros Jazmín",
  tagline: { es: "Viveros y floristería desde 1992", va: "Viver i floristeria des de 1992" },
  address: "Calle Río Anna 135, 12006 Castelló de la Plana",
  phone: "636 54 35 66",
  phoneIntl: "+34636543566",
  email: "jazminfloristeria@hotmail.com",
  hours: {
    es: "Lunes a sábado: 8:30–13:30 y 16:00–20:00 · Domingo y festivos: 9:00–13:00",
    va: "Dilluns a dissabte: 8:30–13:30 i 16:00–20:00 · Diumenge i festius: 9:00–13:00"
  },
  mapsUrl: "https://www.google.com/maps/place/Viveros+JAZM%C3%8DN/@39.9855612,-0.0704806,17z/"
};

const CATEGORIES = [
  { id: "interior",  world: "vivero",      es: "Plantas de interior",   va: "Plantes d'interior",   en: "Indoor plants" },
  { id: "exterior",  world: "vivero",      es: "Plantas de exterior",   va: "Plantes d'exterior",   en: "Outdoor plants" },
  { id: "arboles",   world: "vivero",      es: "Árboles y arbustos",    va: "Arbres i arbustos",    en: "Trees & shrubs" },
  { id: "sustratos", world: "vivero",      es: "Sustratos y abonos",    va: "Substrats i adobs",    en: "Soil & fertilisers" },
  { id: "macetas",   world: "vivero",      es: "Macetas y jardinería",  va: "Testos i jardineria",  en: "Pots & gardening" },
  { id: "flores",    world: "floristeria", es: "Flores de temporada",   va: "Flors de temporada",   en: "Seasonal flowers" }
];

/* ----- Home delivery -----
   Local delivery zone: Castelló de la Plana + towns within ~7 km.
   `min` is the minimum order (in €) for home delivery (free above it).
   Edit the `zone` list to add/remove postal codes you deliver to. */
const DELIVERY = {
  min: 40,
  zone: [
    { cp: "12001", town: "Castelló de la Plana" },
    { cp: "12002", town: "Castelló de la Plana" },
    { cp: "12003", town: "Castelló de la Plana" },
    { cp: "12004", town: "Castelló de la Plana" },
    { cp: "12005", town: "Castelló de la Plana" },
    { cp: "12006", town: "Castelló de la Plana" },
    { cp: "12100", town: "El Grau de Castelló" },
    { cp: "12550", town: "Almassora" },
    { cp: "12190", town: "Borriol" }
  ]
};

/* Product images: themed SVG data-URLs are generated at runtime
   from product.imgSeed so the site is fully self-contained.
   To use real photos, set product.img to a URL — the admin page
   (admin.html) does this automatically. */

// `let` (not const) so the admin can replace the catalog at runtime.
// SEED_PRODUCTS is kept frozen so we can always restore the original.
let PRODUCTS = [
  // ===== INTERIOR (10) =====
  { id: "int-01", cat: "interior", price: 24.90, stock: 12, imgSeed: 130,
    name: { es: "Monstera Deliciosa", va: "Monstera Deliciosa" },
    desc: {
      es: "La icónica costilla de Adán. Hojas perforadas espectaculares, perfecta para dar un toque tropical a cualquier estancia luminosa. Riego moderado.",
      va: "La icònica costella d'Adam. Fulles perforades espectaculars, perfecta per a donar un toc tropical a qualsevol estança lluminosa. Reg moderat."
    } },
  { id: "int-02", cat: "interior", price: 39.50, stock: 6, imgSeed: 120,
    name: { es: "Ficus Lyrata (Pandurata)", va: "Ficus Lyrata (Pandurata)" },
    desc: {
      es: "Árbol de hojas grandes en forma de lira. Estiliza cualquier salón. Le encanta la luz indirecta brillante.",
      va: "Arbre de fulles grans en forma de lira. Estilitza qualsevol saló. Li encanta la llum indirecta brillant."
    } },
  { id: "int-03", cat: "interior", price: 8.90, stock: 40, imgSeed: 110,
    name: { es: "Potos (Pothos)", va: "Potus (Pothos)" },
    desc: {
      es: "La planta colgante más agradecida. Purifica el aire y crece rápido con muy pocos cuidados.",
      va: "La planta penjant més agraïda. Purifica l'aire i creix ràpid amb molt pocs cures."
    } },
  { id: "int-04", cat: "interior", price: 14.50, stock: 18, imgSeed: 90,
    name: { es: "Sansevieria (Lengua de Suegra)", va: "Sanseviera (Llengua de Sogra)" },
    desc: {
      es: "Resistente, elegante y casi indestructible. Ideal para principiantes y espacios con poca luz.",
      va: "Resistent, elegant i quasi indestructible. Ideal per a principiants i espais amb poca llum."
    } },
  { id: "int-05", cat: "interior", price: 18.00, stock: 15, imgSeed: 140,
    name: { es: "Spathiphyllum (Cuna de Moisés)", va: "Spathiphyllum (Bressol de Moisés)" },
    desc: {
      es: "Hojas verde brillante y flores blancas elegantes. Excelente purificadora del aire.",
      va: "Fulles verd brillant i flors blanques elegants. Excel·lent purificadora de l'aire."
    } },
  { id: "int-06", cat: "interior", price: 6.50, stock: 50, imgSeed: 60,
    name: { es: "Cactus surtidos (maceta 10cm)", va: "Cactus assortits (test 10cm)" },
    desc: {
      es: "Selección de cactus pequeños en macetas decorativas. Mínimos cuidados, máximo carácter.",
      va: "Selecció de cactus xicotets en testos decoratius. Mínims cures, màxim caràcter."
    } },
  { id: "int-07", cat: "interior", price: 12.00, stock: 22, imgSeed: 100,
    name: { es: "Aloe Vera", va: "Aloe Vera" },
    desc: {
      es: "Suculenta medicinal con múltiples propiedades. Requiere mucha luz y poco riego.",
      va: "Suculenta medicinal amb múltiples propietats. Requereix molta llum i poc reg."
    } },
  { id: "int-08", cat: "interior", price: 22.00, stock: 10, imgSeed: 160,
    name: { es: "Calathea Orbifolia", va: "Calathea Orbifolia" },
    desc: {
      es: "Hojas redondeadas con rayas plateadas. Una joya para amantes del follaje exótico.",
      va: "Fulles arredonides amb ratlles platejades. Una joia per a amants del fullatge exòtic."
    } },
  { id: "int-09", cat: "interior", price: 16.90, stock: 30, imgSeed: 300,
    name: { es: "Orquídea Phalaenopsis", va: "Orquídia Phalaenopsis" },
    desc: {
      es: "La orquídea más elegante y duradera. Floración prolongada en tonos blancos, rosas o lilas.",
      va: "L'orquídia més elegant i duradora. Floració prolongada en tons blancs, roses o liles."
    } },
  { id: "int-10", cat: "interior", price: 11.50, stock: 24, imgSeed: 115,
    name: { es: "Helecho de Boston", va: "Falguera de Boston" },
    desc: {
      es: "Follaje frondoso y aireado. Perfecto para baños y zonas con humedad alta.",
      va: "Fullatge frondós i airejat. Perfecte per a banys i zones amb humitat alta."
    } },

  // ===== EXTERIOR (10) =====
  { id: "ext-01", cat: "exterior", price: 7.50, stock: 60, imgSeed: 270,
    name: { es: "Lavanda", va: "Espígol" },
    desc: {
      es: "Aroma inconfundible y flores moradas. Atrae polinizadores y tolera muy bien la sequía.",
      va: "Aroma inconfusible i flors morades. Atrau pol·linitzadors i tolera molt bé la sequera."
    } },
  { id: "ext-02", cat: "exterior", price: 5.90, stock: 80, imgSeed: 80,
    name: { es: "Romero", va: "Romer" },
    desc: {
      es: "Aromática mediterránea imprescindible. Resistente y útil tanto en jardín como en cocina.",
      va: "Aromàtica mediterrània imprescindible. Resistent i útil tant al jardí com a la cuina."
    } },
  { id: "ext-03", cat: "exterior", price: 4.50, stock: 100, imgSeed: 350,
    name: { es: "Geranios (variedades)", va: "Geranis (varietats)" },
    desc: {
      es: "El clásico de los balcones mediterráneos. Floración abundante de primavera a otoño.",
      va: "El clàssic dels balcons mediterranis. Floració abundant de primavera a tardor."
    } },
  { id: "ext-04", cat: "exterior", price: 13.50, stock: 18, imgSeed: 40,
    name: { es: "Jazmín blanco", va: "Gessamí blanc" },
    desc: {
      es: "Nuestra planta insignia. Flores blancas perfumadas que llenan el jardín de aroma en verano.",
      va: "La nostra planta insígnia. Flors blanques perfumades que omplen el jardí d'aroma a l'estiu."
    } },
  { id: "ext-05", cat: "exterior", price: 19.90, stock: 14, imgSeed: 320,
    name: { es: "Buganvilla", va: "Bugamvíl·lia" },
    desc: {
      es: "Espectaculares brácteas en fucsia, rojo o naranja. Resistente al calor y a la sal marina.",
      va: "Espectaculars bràctees en fucsia, roig o taronja. Resistent a la calor i a la sal marina."
    } },
  { id: "ext-06", cat: "exterior", price: 15.00, stock: 12, imgSeed: 290,
    name: { es: "Hortensia", va: "Hortènsia" },
    desc: {
      es: "Grandes inflorescencias en azul, rosa o blanco. Prefiere semisombra y riego constante.",
      va: "Grans inflorescències en blau, rosa o blanc. Prefereix semiombra i reg constant."
    } },
  { id: "ext-07", cat: "exterior", price: 21.50, stock: 9, imgSeed: 340,
    name: { es: "Rosal trepador", va: "Roser enfiladís" },
    desc: {
      es: "Para pérgolas, vallas y muros. Disponible en múltiples colores y variedades aromáticas.",
      va: "Per a pèrgoles, tanques i murs. Disponible en múltiples colors i varietats aromàtiques."
    } },
  { id: "ext-08", cat: "exterior", price: 12.00, stock: 16, imgSeed: 310,
    name: { es: "Hibisco", va: "Hibisc" },
    desc: {
      es: "Grandes flores tropicales en rojo, rosa o amarillo. Perfecto para zonas soleadas.",
      va: "Grans flors tropicals en roig, rosa o groc. Perfecte per a zones assolellades."
    } },
  { id: "ext-09", cat: "exterior", price: 3.50, stock: 120, imgSeed: 70,
    name: { es: "Margaritas", va: "Margarides" },
    desc: {
      es: "Flores alegres de pétalos blancos y centro amarillo. Las imprescindibles del jardín.",
      va: "Flors alegres de pètals blancs i centre groc. Les imprescindibles del jardí."
    } },
  { id: "ext-10", cat: "exterior", price: 6.90, stock: 70, imgSeed: 330,
    name: { es: "Petunias colgantes", va: "Petúnies penjants" },
    desc: {
      es: "Cascadas de flores en jardineras y balcones. Floración continua todo el verano.",
      va: "Cascades de flors en jardineres i balcons. Floració contínua tot l'estiu."
    } },

  // ===== ÁRBOLES (8) =====
  { id: "arb-01", cat: "arboles", price: 89.00, stock: 5, imgSeed: 95,
    name: { es: "Olivo decorativo", va: "Olivera decorativa" },
    desc: {
      es: "Pieza única de carácter mediterráneo. Ideal como ejemplar central en jardines y patios.",
      va: "Peça única de caràcter mediterrani. Ideal com a exemplar central en jardins i patis."
    } },
  { id: "arb-02", cat: "arboles", price: 45.00, stock: 8, imgSeed: 55,
    name: { es: "Limonero", va: "Llimera" },
    desc: {
      es: "Frutal mediterráneo por excelencia. Produce limones durante gran parte del año.",
      va: "Fruiter mediterrani per excel·lència. Produeix llimes durant gran part de l'any."
    } },
  { id: "arb-03", cat: "arboles", price: 49.00, stock: 7, imgSeed: 30,
    name: { es: "Naranjo", va: "Taronger" },
    desc: {
      es: "Aromáticas flores de azahar y deliciosas naranjas. Un clásico del jardín valenciano.",
      va: "Aromàtiques flors de tarongina i delicioses taronges. Un clàssic del jardí valencià."
    } },
  { id: "arb-04", cat: "arboles", price: 32.00, stock: 12, imgSeed: 145,
    name: { es: "Ciprés", va: "Xiprer" },
    desc: {
      es: "Perfecto para setos y como ejemplar aislado. Crecimiento rápido y porte elegante.",
      va: "Perfecte per a tanques i com a exemplar aïllat. Creixement ràpid i port elegant."
    } },
  { id: "arb-05", cat: "arboles", price: 17.00, stock: 20, imgSeed: 0,
    name: { es: "Adelfa", va: "Baladre" },
    desc: {
      es: "Arbusto mediterráneo muy resistente. Floración espectacular en rojo, rosa o blanco.",
      va: "Arbust mediterrani molt resistent. Floració espectacular en roig, rosa o blanc."
    } },
  { id: "arb-06", cat: "arboles", price: 75.00, stock: 4, imgSeed: 305,
    name: { es: "Magnolia grandiflora", va: "Magnòlia grandiflora" },
    desc: {
      es: "Árbol majestuoso de flores blancas y aromáticas. Ejemplar que marca el paisaje.",
      va: "Arbre majestuós de flors blanques i aromàtiques. Exemplar que marca el paisatge."
    } },
  { id: "arb-07", cat: "arboles", price: 120.00, stock: 3, imgSeed: 75,
    name: { es: "Palmera Phoenix", va: "Palmera Phoenix" },
    desc: {
      es: "Aporta carácter tropical a cualquier jardín. Muy resistente a la salinidad y al calor.",
      va: "Aporta caràcter tropical a qualsevol jardí. Molt resistent a la salinitat i a la calor."
    } },
  { id: "arb-08", cat: "arboles", price: 14.00, stock: 25, imgSeed: 125,
    name: { es: "Boj", va: "Boix" },
    desc: {
      es: "Ideal para setos formales y topiaria. Hoja perenne pequeña y muy compacta.",
      va: "Ideal per a tanques formals i topiària. Fulla perenne xicoteta i molt compacta."
    } },

  // ===== SUSTRATOS (5) =====
  { id: "sus-01", cat: "sustratos", price: 8.50, stock: 50, imgSeed: 25,
    name: { es: "Sustrato universal 20L", va: "Substrat universal 20L" },
    desc: {
      es: "Mezcla equilibrada apta para la mayoría de plantas. Buen drenaje y nutrición.",
      va: "Mescla equilibrada apta per a la majoria de plantes. Bon drenatge i nutrició."
    } },
  { id: "sus-02", cat: "sustratos", price: 4.90, stock: 40, imgSeed: 20,
    name: { es: "Sustrato para cactus 5L", va: "Substrat per a cactus 5L" },
    desc: {
      es: "Mezcla mineral con perlita y arena. Drenaje óptimo para suculentas y cactus.",
      va: "Mescla mineral amb perlita i arena. Drenatge òptim per a suculentes i cactus."
    } },
  { id: "sus-03", cat: "sustratos", price: 18.90, stock: 25, imgSeed: 15,
    name: { es: "Turba rubia 50L", va: "Torba rossa 50L" },
    desc: {
      es: "Turba de calidad profesional para semilleros y plantación. Estructura aireada.",
      va: "Torba de qualitat professional per a planters i plantació. Estructura airejada."
    } },
  { id: "sus-04", cat: "sustratos", price: 12.50, stock: 30, imgSeed: 50,
    name: { es: "Abono líquido universal 1L", va: "Adob líquid universal 1L" },
    desc: {
      es: "Aporta los nutrientes esenciales para un crecimiento sano. Dosificador incluido.",
      va: "Aporta els nutrients essencials per a un creixement sa. Dosificador inclòs."
    } },
  { id: "sus-05", cat: "sustratos", price: 9.90, stock: 35, imgSeed: 35,
    name: { es: "Humus de lombriz 5kg", va: "Humus de cuc 5kg" },
    desc: {
      es: "Abono orgánico 100% natural. Mejora la estructura del suelo y la microbiota.",
      va: "Adob orgànic 100% natural. Millora l'estructura del sòl i la microbiota."
    } },

  // ===== MACETAS (5) =====
  { id: "mac-01", cat: "macetas", price: 9.50, stock: 40, imgSeed: 22,
    name: { es: "Maceta terracota 25cm", va: "Test terracota 25cm" },
    desc: {
      es: "Clásica maceta de barro cocido. Transpirable y de larga duración.",
      va: "Clàssic test de fang cuit. Transpirable i de llarga durada."
    } },
  { id: "mac-02", cat: "macetas", price: 24.90, stock: 18, imgSeed: 200,
    name: { es: "Maceta cerámica decorativa", va: "Test ceràmic decoratiu" },
    desc: {
      es: "Cerámica esmaltada en varios colores. Acabado mate, ideal para interior.",
      va: "Ceràmica esmaltada en diversos colors. Acabat mat, ideal per a interior."
    } },
  { id: "mac-03", cat: "macetas", price: 17.50, stock: 22, imgSeed: 18,
    name: { es: "Jardinera rectangular 60cm", va: "Jardinera rectangular 60cm" },
    desc: {
      es: "Perfecta para balcones y terrazas. Plato recogegotas integrado.",
      va: "Perfecta per a balcons i terrasses. Plat arreplegagotes integrat."
    } },
  { id: "mac-04", cat: "macetas", price: 29.00, stock: 12, imgSeed: 250,
    name: { es: "Set de herramientas de jardín", va: "Joc d'eines de jardí" },
    desc: {
      es: "Pala, transplantador y rastrillo. Mango ergonómico de madera.",
      va: "Pala, transplantador i rasclet. Mànec ergonòmic de fusta."
    } },
  { id: "mac-05", cat: "macetas", price: 22.50, stock: 14, imgSeed: 240,
    name: { es: "Regadera metálica 5L", va: "Regadora metàl·lica 5L" },
    desc: {
      es: "Diseño clásico en zinc. Roseta desmontable para riego suave.",
      va: "Disseny clàssic en zinc. Roseta desmuntable per a un reg suau."
    } },

  // ===== FLORES TEMPORADA (5) =====
  { id: "flo-01", cat: "flores", price: 28.00, stock: 8, imgSeed: 320,
    name: { es: "Ramo de temporada", va: "Ram de temporada" },
    desc: {
      es: "Selección floral fresca de nuestros mejores proveedores. Compuesto a mano por nuestra floristería.",
      va: "Selecció floral fresca dels nostres millors proveïdors. Compost a mà per la nostra floristeria."
    } },
  { id: "flo-02", cat: "flores", price: 3.50, stock: 120, imgSeed: 290,
    name: { es: "Pensamientos", va: "Pensaments" },
    desc: {
      es: "Las flores del invierno. Resisten el frío y aportan color cuando todo descansa.",
      va: "Les flors de l'hivern. Resistixen el fred i aporten color quan tot descansa."
    } },
  { id: "flo-03", cat: "flores", price: 6.90, stock: 40, imgSeed: 330,
    name: { es: "Ciclamen", va: "Ciclamen" },
    desc: {
      es: "Floración invernal espectacular en macetas. Tonos rosados, blancos y rojos.",
      va: "Floració hivernal espectacular en testos. Tons rosats, blancs i rojos."
    } },
  { id: "flo-04", cat: "flores", price: 9.50, stock: 30, imgSeed: 45,
    name: { es: "Crisantemos", va: "Crisantems" },
    desc: {
      es: "Disponibles en gran variedad de colores. La flor del otoño por excelencia.",
      va: "Disponibles en gran varietat de colors. La flor de la tardor per excel·lència."
    } },
  { id: "flo-05", cat: "flores", price: 11.90, stock: 20, imgSeed: 5,
    name: { es: "Poinsettia (Flor de Pascua)", va: "Poinsettia (Flor de Pasqua)" },
    desc: {
      es: "La planta navideña por antonomasia. Sus brácteas rojas alegran cualquier rincón.",
      va: "La planta nadalenca per antonomàsia. Les seues bràctees roges alegren qualsevol racó."
    } }
];

// Frozen reference copy used by the admin "Reset to defaults" action.
const SEED_PRODUCTS = JSON.parse(JSON.stringify(PRODUCTS));

/* ========= UI string translations ========= */
const I18N = {
  es: {
    "nav.home": "Inicio",
    "nav.shop": "Tienda",
    "nav.vivero": "Vivero",
    "nav.floristeria": "Floristería",
    "nav.plantas": "Plantas",
    "nav.flores": "Flores",
    "nav.decoracion": "Decoración",
    "nav.eventos": "Eventos",
    "nav.seeAll": "Ver todo",
    "nav.about": "Sobre nosotros",
    "nav.contact": "Contacto",
    "world.vivero": "Vivero & Jardín",
    "world.floristeria": "Floristería & Flores",
    "world.viveroTag": "Plantas, árboles y todo para tu jardín",
    "world.floristeriaTag": "Ramos, flores y encargos especiales",
    "shop.occasions.title": "Ocasiones especiales",
    "shop.occasions.text": "Bodas, eventos y funerales: flores y decoración por encargo.",
    "shop.occasions.cta": "Pedir asesoramiento",
    "nav.cart": "Carrito",
    "common.viewMore": "Ver más",
    "common.buy": "Comprar",
    "common.addToCart": "Añadir al carrito",
    "common.added": "Añadido al carrito",
    "common.favorite": "Añadir a favoritos",
    "common.outOfStock": "Sin stock",
    "favs.title": "Tus favoritos",
    "favs.sub": "Los productos que has guardado para más tarde.",
    "favs.empty.title": "Aún no tienes favoritos",
    "favs.empty.text": "Pulsa el corazón en cualquier producto para guardarlo aquí.",
    "favs.empty.cta": "Explorar tienda",
    "nav.favs": "Favoritos",
    "common.inStock": "En stock",
    "common.units": "unidades",
    "common.price": "Precio",
    "common.quantity": "Cantidad",
    "common.subtotal": "Subtotal",
    "common.total": "Total",
    "common.continue": "Continuar comprando",
    "common.checkout": "Tramitar pedido",
    "common.remove": "Eliminar",
    "common.back": "Volver",
    "common.send": "Enviar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "filter.price": "Precio",
    "filter.from": "Desde",
    "filter.to": "Hasta",
    "filter.type": "Tipo",
    "filter.flowerType": "Tipo de flor",
    "filter.color": "Color",
    "common.search": "Buscar productos…",
    "header.favorites": "Favoritos",
    "header.cart": "Carrito",
    "search.recent": "Búsquedas recientes",
    "search.products": "Productos",
    "search.categories": "Categorías",
    "search.none": "Sin resultados. Prueba otra palabra.",
    "search.seeAll": "Ver todo para",
    "common.openMaps": "Abrir en Google Maps",
    "common.callUs": "Llámanos",
    "common.email": "Escríbenos",
    "common.hours": "Horario",
    "common.address": "Dirección",
    "common.phone": "Teléfono",
    "common.related": "También te puede interesar",
    "home.hero.eyebrow": "Plantas & Flores · Castelló · 1992",
    "home.hero.title": "<em>Plantas</em> para tu casa,<br><em>flores</em> para tu día.",
    "home.hero.lead": "Vivero y floristería en el corazón de Castelló de la Plana. Macetas, ramos, flores de temporada y la planta perfecta para cada rincón.",
    "home.hero.subtitle": "Plantas, árboles, sustratos y flores de temporada. Cultivamos con cariño desde 1992.",
    "home.hero.cta": "Ver la tienda",
    "home.featured": "Destacados",
    "home.categories": "Categorías",
    "home.promise": "<em>Verde</em> para tu casa.<br><em>Flores</em> para tus momentos.",
    "home.search.go": "Buscar",
    "home.shop.eyebrow": "La tienda",
    "home.shop.title": "Compra ahora",
    "home.shop.all": "Ver toda la tienda",
    "home.shop.empty": "Pronto más productos por aquí.",
    "home.dept.all": "Todo",
    "home.dept.vivero": "Plantas & Jardín",
    "home.dept.floristeria": "Flores & Eventos",
    "home.depts.eyebrow": "Dos casas, una tienda",
    "home.depts.title": "¿Qué buscas hoy?",
    "home.shopcat.title": "Compra por categoría",
    "home.depts.viveroSub": "Interior, exterior, árboles, macetas y sustratos",
    "home.depts.floresSub": "Ramos, flores de temporada, bodas y eventos",
    "home.trust.delivery": "Entrega en Castelló (7 km)",
    "home.trust.pickup": "Recogida en tienda",
    "home.trust.secure": "Pago seguro",
    "home.trust.since": "Floristería desde 1992",
    "home.events.eyebrow": "Para tu evento",
    "home.events.title": "<em>Flores</em> que cuentan<br>tu historia",
    "home.events.text": "Bodas, celebraciones, homenajes y empresas. Te asesoramos sin compromiso.",
    "home.events.cta": "Pídenos presupuesto",
    "home.featured.heading": "<em>Una selección</em><br>del mes",
    "home.story.heading": "<em>Tres décadas</em><br>cuidando plantas",
    "home.story.quote": "«Cada planta lleva el mismo cuidado que la primera de 1992.»",
    "home.visit.heading": "<em>Ven a vernos</em><br>al vivero",
    "about.h1": "<em>Tres décadas</em> cultivando",
    "about.h2.story": "<em>Desde 1992,</em><br>un proyecto familiar",
    "about.h2.visit": "<em>Ven a vernos</em><br>al vivero",
    "contact.h1": "<em>Hablemos</em>",
    "contact.h2.location": "<em>Castelló</em><br>de la Plana",
    "auth.google.signin": "Continuar con Google",
    "auth.google.signup": "Registrarse con Google",
    "auth.or.email": "o con tu correo",
    "home.stats.years": "Años cultivando",
    "home.stats.species": "Variedades en stock",
    "home.stats.founded": "Proyecto familiar",
    "home.stats.region": "Castelló de la Plana",
    "home.story.title": "Nuestra historia",
    "home.story.text": "Jazmín nace en 1992 como un proyecto familiar: un vivero y una floristería en Castelló. Tres décadas después seguimos cuidando cada planta y componiendo cada ramo como el primer día.",
    "home.story.cta": "Conoce más",
    "home.visit.title": "Visítanos en el vivero",
    "home.visit.text": "Pásate por nuestras instalaciones en Castelló de la Plana. Te asesoramos sobre la planta perfecta para cada espacio.",
    "shop.title": "Nuestra tienda",
    "shop.subtitle": "Más de 40 productos seleccionados. Recoge en tienda o solicita el envío.",
    "shop.empty": "No hay productos para esta selección.",
    "cart.title": "Tu carrito",
    "cart.empty": "Tu carrito está vacío.",
    "cart.emptyCta": "Ir a la tienda",
    "cart.total": "Total",
    "cart.checkout": "Tramitar pedido",
    "checkout.title": "Tramitar pedido",
    "checkout.details": "Datos de contacto",
    "checkout.name": "Nombre completo",
    "checkout.emailLbl": "Correo electrónico",
    "checkout.phoneLbl": "Teléfono",
    "checkout.delivery": "Recogida / Envío",
    "checkout.pickup": "Recoger en tienda (gratis)",
    "checkout.ship": "Envío a domicilio",
    "checkout.address": "Dirección de envío",
    "checkout.freeShipTag": "Gratis desde 40 €",
    "checkout.cpTown": "Código postal o población",
    "checkout.locPlaceholder": "Escribe tu CP o población: 12005, Almassora…",
    "checkout.street": "Calle y número",
    "checkout.streetPlaceholder": "p. ej. Calle Mayor 12, 3ºA",
    "checkout.minNotice": "El envío a domicilio está disponible para pedidos desde 40 €.",
    "checkout.youNeed": "Te faltan",
    "checkout.forFreeShip": "para poder pedir con envío.",
    "checkout.inZone": "¡Repartimos en tu zona!",
    "checkout.outZone": "Esta dirección está fuera de nuestra zona de reparto (7 km). Elige recogida en tienda o escríbenos.",
    "checkout.notes": "Notas para el pedido",
    "checkout.summary": "Resumen del pedido",
    "checkout.submit": "Enviar pedido",
    "checkout.success.title": "¡Pedido recibido!",
    "checkout.success.text": "Gracias por confiar en Viveros Jazmín. Nos pondremos en contacto contigo en menos de 24 horas para confirmar tu pedido.",
    "checkout.success.ref": "Referencia",
    "checkout.success.back": "Volver al inicio",
    "about.title": "Sobre Jazmín",
    "about.p1": "Viveros Jazmín nace en el año 1992, momento en el que una joven pareja, ambos trabajadores del sector ornamental, contraen matrimonio y deciden emprender la aventura de crear un proyecto que les permita trabajar juntos poniendo en práctica todos los conocimientos adquiridos hasta entonces.",
    "about.p2": "Abren una pequeña floristería y comienzan a cultivar plantas en un terreno propiedad de la familia situado en la Cuadra de Los Cubos. Años más tarde la floristería se traslada a un local mucho más amplio y el vivero amplía su oferta de variedades.",
    "about.p3": "Actualmente, todo el equipo que compone la empresa trabaja con esfuerzo e ilusión para poder ofrecer, tanto a profesionales como a aficionados de la jardinería y floristería, gran variedad de productos.",
    "about.p4": "A lo largo de estos años hemos creado vínculos afectivos con nuestros clientes con quienes compartimos momentos muy agradables. Gracias a ellos y a sus experiencias y conocimientos sobre las plantas continuamos aprendiendo cada día.",
    "contact.title": "Contacto",
    "contact.subtitle": "¿Tienes una pregunta o un encargo especial? Estaremos encantados de ayudarte.",
    "contact.form.name": "Tu nombre",
    "contact.form.email": "Tu correo",
    "contact.form.message": "Mensaje",
    "contact.form.submit": "Enviar mensaje",
    "contact.form.success": "¡Gracias! Te responderemos lo antes posible.",
    "contact.form.phone": "Tu teléfono (opcional)",
    "contact.form.type": "¿En qué podemos ayudarte?",
    "contact.consult": "¿Preparas una boda, un evento o una despedida? Componemos ramos, centros y decoración floral por encargo. Cuéntanos qué necesitas y te asesoramos sin compromiso.",
    "contact.type.general": "Consulta general",
    "contact.type.boda": "Boda",
    "contact.type.evento": "Evento o celebración",
    "contact.type.funeral": "Funeral / duelo",
    "contact.type.empresa": "Empresa / negocio",
    "contact.type.otro": "Otro",
    "brand.sub": "Plantas & Flores · Castelló · Desde 1992",
    "brand.subShort": "Plantas & Flores",
    "footer.tagline": "Plantas, flores y ramos en Castelló de la Plana desde 1992.",
    "footer.shop": "Tienda",
    "footer.info": "Información",
    "footer.find": "Encuéntranos",
    "footer.copy": "Todos los derechos reservados.",
    "auth.signin": "Entrar",
    "auth.signup": "Crear cuenta",
    "auth.login.title": "Bienvenido de nuevo",
    "auth.login.sub": "Accede a tu cuenta para gestionar tus pedidos.",
    "auth.register.title": "Crea tu cuenta",
    "auth.register.sub": "Guarda tus pedidos y agiliza la compra la próxima vez.",
    "auth.aside.title": "Tu jardín, a un clic.",
    "auth.aside.text": "Crea una cuenta para guardar tus direcciones, tus pedidos y tus plantas favoritas.",
    "auth.name": "Nombre completo",
    "auth.password": "Contraseña",
    "auth.password.confirm": "Confirmar contraseña",
    "auth.alt.toregister": "¿Aún no tienes cuenta?",
    "auth.alt.tologin": "¿Ya tienes cuenta?",
    "auth.alt.toregister.cta": "Crear cuenta",
    "auth.alt.tologin.cta": "Entrar",
    "auth.err.missing": "Por favor rellena todos los campos obligatorios.",
    "auth.err.short": "La contraseña debe tener al menos 6 caracteres.",
    "auth.err.mismatch": "Las contraseñas no coinciden.",
    "auth.err.exists": "Ya existe una cuenta con este correo.",
    "auth.err.nouser": "No encontramos una cuenta con este correo.",
    "auth.err.badpass": "La contraseña no es correcta.",
    "auth.err.confirm": "Te hemos enviado un correo para confirmar tu cuenta. Revisa tu bandeja de entrada.",
    "auth.err.unknown": "Algo ha fallado. Vuelve a intentarlo.",
    "account.title": "Mi cuenta",
    "account.welcome": "Hola",
    "account.menu.profile": "Perfil",
    "account.menu.orders": "Mis pedidos",
    "account.menu.favs": "Favoritos",
    "account.menu.cart": "Mi cesta",
    "account.menu.logout": "Cerrar sesión",
    "account.menu.delete": "Eliminar cuenta",
    "account.cart.title": "Tu cesta actual",
    "account.cart.sub": "Lo que tienes en la cesta ahora mismo.",
    "account.cart.view": "Ver cesta",
    "account.profile.title": "Tus datos",
    "account.profile.sub": "Mantén tu información al día. Solo tú puedes ver estos datos.",
    "account.profile.emailHint": "Por seguridad, el email no se puede cambiar desde aquí.",
    "account.profile.save": "Guardar cambios",
    "account.profile.saved": "Guardado",
    "account.orders.title": "Mis pedidos",
    "account.orders.sub": "Todos tus pedidos, los recientes y los de hace tiempo.",
    "account.orders.empty": "Aún no has realizado ningún pedido.",
    "account.favs.title": "Productos guardados",
    "account.favs.empty": "Aún no has guardado ningún producto. Pulsa el corazón en cualquier ficha para añadirlo aquí.",
    "account.member": "Cliente desde",
    "order.status.pending":   "Pendiente",
    "order.status.confirmed": "Confirmado",
    "order.status.paid":      "Pagado",
    "order.status.shipped":   "Enviado",
    "order.status.delivered": "Entregado",
    "order.status.cancelled": "Cancelado",
    "product.origin": "Origen",
    "product.like": "Guardar",
    "product.liked": "Guardado",
    "product.choosePot": "Elige tu maceta",
    "product.noPot": "Sin maceta",
    "product.free": "Gratis",
    "likes.toast.title": "Guardado en favoritos",
    "likes.toast.text": "Crea una cuenta para conservar tus favoritos en todos tus dispositivos.",
    "likes.toast.cta": "Crear cuenta",
    "jobs.title": "Trabaja con nosotros",
    "jobs.hero.eyebrow": "Únete al equipo",
    "jobs.hero.title": "<em>Trabaja</em> con nosotros",
    "jobs.hero.lead": "Cultivamos plantas, relaciones y un equipo que disfruta lo que hace.",
    "jobs.card.tag": "Plaza abierta",
    "jobs.card.title": "<em>Auxiliar</em> de vivero y floristería",
    "jobs.card.meta.location": "📍 Castelló de la Plana",
    "jobs.card.meta.hours": "⏱ Jornada completa",
    "jobs.card.meta.start": "📅 Incorporación inmediata",
    "jobs.duties.heading": "Qué harás",
    "jobs.duties.item1": "Atender a clientes en el vivero y la floristería, asesorando sobre plantas, sustratos y cuidados.",
    "jobs.duties.item2": "Preparar y mantener los productos en la zona de venta (plantas, macetas, sustratos, decoración).",
    "jobs.duties.item3": "Componer ramos, centros y arreglos sencillos para particulares y eventos.",
    "jobs.duties.item4": "Apoyar en tareas de mantenimiento del vivero: riego, trasplantes, control de stock.",
    "jobs.duties.item5": "Colaborar puntualmente en entregas locales y montajes para clientes.",
    "jobs.seek.heading": "Lo que buscamos",
    "jobs.seek.item1": "Pasión por las plantas y por el trato con personas.",
    "jobs.seek.item2": "Disponibilidad para horario partido, algunos sábados completos y domingos puntuales (festivos especiales como San Valentín, Día de la Madre, Todos los Santos).",
    "jobs.seek.item3": "Castellano y, preferiblemente, valenciano para comunicarte con la clientela local.",
    "jobs.seek.item4": "No es imprescindible experiencia previa — formamos a quien tenga ganas y actitud.",
    "jobs.offer.heading": "Lo que ofrecemos",
    "jobs.offer.item1": "Equipo familiar, ambiente cuidado, formación práctica.",
    "jobs.offer.item2": "Contrato indefinido tras periodo de prueba.",
    "jobs.offer.item3": "Descuentos en planta y producto.",
    "jobs.offer.item4": "Castelló de la Plana — sin desplazamientos largos, a 5 min del centro.",
    "jobs.apply.cta": "Aplicar a esta plaza",
    "jobs.apply.spont": "O envía una candidatura espontánea",
    "jobs.refer": "¿No es para ti pero conoces a alguien? Compártelo — gracias 🌿",
    "jobs.backToOffer": "← Volver a la oferta",
    "jobs.apply.title": "<em>Tu</em> candidatura",
    "jobs.apply.lead": "Solo unos pocos pasos. Tus respuestas viajan cifradas y solo las leemos nosotros.",
    "jobs.stepper.contact": "Contacto",
    "jobs.stepper.cv": "CV",
    "jobs.stepper.about": "Sobre ti",
    "jobs.step1.note": "Solo necesitamos email y teléfono para responderte.",
    "jobs.cvStep.title": "Tu CV",
    "jobs.cvStep.note": "Si tienes un CV, súbelo. Si no, también puedes continuar — te haremos algunas preguntas para conocerte.",
    "jobs.noCv.small": "Te haremos unas preguntas",
    "jobs.cvPick": "Elegir archivo PDF…",
    "jobs.cvSelectedLbl": "CV seleccionado:",
    "jobs.privacyLine": "Al enviar aceptas nuestra <a href=\"privacidad.html\">Política de Privacidad</a>.",
    "jobs.success.home": "Volver al inicio",
    "jobs.subtitle": "Únete a un equipo familiar que cultiva con cariño desde 1992.",
    "jobs.intro": "Si te apasionan las plantas y el trato con los clientes, queremos conocerte. Envíanos tu candidatura — con o sin CV.",
    "jobs.step": "Paso",
    "jobs.of": "de",
    "jobs.step1.title": "Tus datos de contacto",
    "jobs.step2.title": "Tu candidatura",
    "jobs.step2.withCv": "Subir CV (PDF)",
    "jobs.step2.withoutCv": "Continuar sin CV",
    "jobs.step2.note": "Si no tienes CV listo, no pasa nada — te haremos unas preguntas para conocerte.",
    "jobs.step3.title": "Cuéntanos un poco más",
    "jobs.step3.optional": "Mensaje (opcional)",
    "jobs.step3.optionalPh": "Cualquier cosa que quieras compartir con nosotros…",
    "jobs.back": "Atrás",
    "jobs.next": "Continuar",
    "jobs.submit": "Enviar candidatura",
    "jobs.success.title": "¡Candidatura recibida!",
    "jobs.success.text": "Gracias por tu interés. La hemos guardado y te contactaremos pronto.",
    "jobs.success.ref": "Referencia",
    "jobs.privacy": "Al enviar aceptas nuestra",
    "jobs.cvLimit": "PDF, hasta 3 MB",
    "jobs.cvSelected": "CV seleccionado",
    "jobs.cvRemove": "Quitar",
    "jobs.required": "Obligatorio",
    "jobs.choose": "Selecciona una opción"
  },
  en: {
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.vivero": "Nursery",
    "nav.floristeria": "Florist",
    "nav.plantas": "Plants",
    "nav.flores": "Flowers",
    "nav.decoracion": "Decor",
    "nav.eventos": "Events",
    "nav.seeAll": "See all",
    "nav.about": "About us",
    "nav.contact": "Contact",
    "world.vivero": "Nursery & Garden",
    "world.floristeria": "Florist & Flowers",
    "world.viveroTag": "Plants, trees and everything for your garden",
    "world.floristeriaTag": "Bouquets, flowers and special orders",
    "shop.occasions.title": "Special occasions",
    "shop.occasions.text": "Weddings, events and funerals: flowers and decoration to order.",
    "shop.occasions.cta": "Request advice",
    "nav.cart": "Cart",
    "common.viewMore": "View more",
    "common.buy": "Buy",
    "common.addToCart": "Add to cart",
    "common.added": "Added to cart",
    "common.favorite": "Add to favourites",
    "common.outOfStock": "Out of stock",
    "favs.title": "Your favourites",
    "favs.sub": "The products you've saved for later.",
    "favs.empty.title": "No favourites yet",
    "favs.empty.text": "Tap the heart on any product to save it here.",
    "favs.empty.cta": "Browse the shop",
    "nav.favs": "Favourites",
    "common.inStock": "In stock",
    "common.units": "units",
    "common.price": "Price",
    "common.quantity": "Quantity",
    "common.subtotal": "Subtotal",
    "common.total": "Total",
    "common.continue": "Continue shopping",
    "common.checkout": "Checkout",
    "common.remove": "Remove",
    "common.back": "Back",
    "common.send": "Send",
    "common.filter": "Filter",
    "common.all": "All",
    "filter.price": "Price",
    "filter.from": "From",
    "filter.to": "To",
    "filter.type": "Type",
    "filter.flowerType": "Flower type",
    "filter.color": "Colour",
    "common.search": "Search products…",
    "header.favorites": "Favorites",
    "header.cart": "Cart",
    "search.recent": "Recent searches",
    "search.products": "Products",
    "search.categories": "Categories",
    "search.none": "No results. Try another word.",
    "search.seeAll": "See all for",
    "common.openMaps": "Open in Google Maps",
    "common.callUs": "Call us",
    "common.email": "Email us",
    "common.hours": "Opening hours",
    "common.address": "Address",
    "common.phone": "Phone",
    "common.related": "You may also like",
    "home.hero.eyebrow": "Plants & Flowers · Castelló · 1992",
    "home.hero.title": "<em>Plants</em> for your home,<br><em>flowers</em> for your day.",
    "home.hero.lead": "Nursery and florist in the heart of Castelló de la Plana. Pots, bouquets, seasonal flowers and the perfect plant for every corner.",
    "home.hero.subtitle": "Plants, trees, substrates and seasonal flowers. Grown with care since 1992.",
    "home.hero.cta": "Visit the shop",
    "home.featured": "Featured",
    "home.categories": "Categories",
    "home.promise": "<em>Green</em> for your home.<br><em>Flowers</em> for your moments.",
    "home.search.go": "Search",
    "home.shop.eyebrow": "The shop",
    "home.shop.title": "Shop now",
    "home.shop.all": "Browse the full shop",
    "home.shop.empty": "More products coming soon.",
    "home.dept.all": "Everything",
    "home.dept.vivero": "Plants & Garden",
    "home.dept.floristeria": "Flowers & Events",
    "home.depts.eyebrow": "Two worlds, one shop",
    "home.depts.title": "What are you looking for today?",
    "home.shopcat.title": "Shop by category",
    "home.depts.viveroSub": "Indoor, outdoor, trees, pots & soil",
    "home.depts.floresSub": "Bouquets, seasonal flowers, weddings & events",
    "home.trust.delivery": "Delivery in Castelló (7 km)",
    "home.trust.pickup": "Collect in store",
    "home.trust.secure": "Secure payment",
    "home.trust.since": "Florist since 1992",
    "home.events.eyebrow": "For your event",
    "home.events.title": "<em>Flowers</em> that tell<br>your story",
    "home.events.text": "Weddings, celebrations, tributes and businesses. Free, no-obligation advice.",
    "home.events.cta": "Request a quote",
    "home.featured.heading": "<em>A selection</em><br>of the month",
    "home.story.heading": "<em>Three decades</em><br>caring for plants",
    "home.story.quote": "“Every plant gets the same care as the very first one back in 1992.”",
    "home.visit.heading": "<em>Come and see us</em><br>at the nursery",
    "about.h1": "<em>Three decades</em> growing",
    "about.h2.story": "<em>Since 1992,</em><br>a family project",
    "about.h2.visit": "<em>Come and see us</em><br>at the nursery",
    "contact.h1": "<em>Let's talk</em>",
    "contact.h2.location": "<em>Castelló</em><br>de la Plana",
    "auth.google.signin": "Continue with Google",
    "auth.google.signup": "Sign up with Google",
    "auth.or.email": "or with your email",
    "home.stats.years": "Years growing",
    "home.stats.species": "Varieties in stock",
    "home.stats.founded": "Family project",
    "home.stats.region": "Castelló de la Plana",
    "home.story.title": "Our story",
    "home.story.text": "Jazmín began in 1992 as a family project: a nursery and a florist in Castelló. Three decades on, we still care for every plant and craft every bouquet as we did on day one.",
    "home.story.cta": "Learn more",
    "home.visit.title": "Visit us at the nursery",
    "home.visit.text": "Come by our premises in Castelló de la Plana. We'll help you find the perfect plant for every space.",
    "shop.title": "Our shop",
    "shop.subtitle": "Over 40 hand-picked products. Pick up in store or get it delivered.",
    "shop.empty": "No products for this selection.",
    "cart.title": "Your cart",
    "cart.empty": "Your cart is empty.",
    "cart.emptyCta": "Go to the shop",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "checkout.title": "Checkout",
    "checkout.details": "Contact details",
    "checkout.name": "Full name",
    "checkout.emailLbl": "Email address",
    "checkout.phoneLbl": "Phone",
    "checkout.delivery": "Pickup / Delivery",
    "checkout.pickup": "Pick up in store (free)",
    "checkout.ship": "Home delivery",
    "checkout.address": "Delivery address",
    "checkout.freeShipTag": "Free from €40",
    "checkout.cpTown": "Postcode or town",
    "checkout.locPlaceholder": "Type your postcode or town: 12005, Almassora…",
    "checkout.street": "Street and number",
    "checkout.streetPlaceholder": "e.g. Calle Mayor 12, 3ºA",
    "checkout.minNotice": "Home delivery is available for orders from €40.",
    "checkout.youNeed": "You need",
    "checkout.forFreeShip": "more to order with delivery.",
    "checkout.inZone": "We deliver to your area!",
    "checkout.outZone": "This address is outside our delivery area (7 km). Choose store pickup or write to us.",
    "checkout.notes": "Order notes",
    "checkout.summary": "Order summary",
    "checkout.submit": "Place order",
    "checkout.success.title": "Order received!",
    "checkout.success.text": "Thank you for trusting Viveros Jazmín. We'll get in touch within 24 hours to confirm your order.",
    "checkout.success.ref": "Reference",
    "checkout.success.back": "Back to home",
    "about.title": "About Jazmín",
    "about.p1": "Viveros Jazmín was born in 1992, when a young couple — both working in the ornamental sector — got married and decided to embark on the adventure of building a project that would let them work together, putting into practice everything they had learned until then.",
    "about.p2": "They opened a small florist and began growing plants on a family-owned plot in La Cuadra de Los Cubos. Years later the florist moved to a much larger space and the nursery expanded its range of varieties.",
    "about.p3": "Today, the whole team works with effort and passion to offer a wide variety of products to both professionals and gardening and floristry enthusiasts.",
    "about.p4": "Over these years we've built close bonds with our customers, sharing many lovely moments. Thanks to them, and to their experiences and knowledge about plants, we keep learning every day.",
    "contact.title": "Contact",
    "contact.subtitle": "Have a question or a special order? We'd be glad to help.",
    "contact.form.name": "Your name",
    "contact.form.email": "Your email",
    "contact.form.message": "Message",
    "contact.form.submit": "Send message",
    "contact.form.success": "Thank you! We'll reply as soon as possible.",
    "contact.form.phone": "Your phone (optional)",
    "contact.form.type": "How can we help you?",
    "contact.consult": "Planning a wedding, an event or a farewell? We create bouquets, centrepieces and floral decoration to order. Tell us what you need and we'll advise you with no obligation.",
    "contact.type.general": "General enquiry",
    "contact.type.boda": "Wedding",
    "contact.type.evento": "Event or celebration",
    "contact.type.funeral": "Funeral / condolence",
    "contact.type.empresa": "Business",
    "contact.type.otro": "Other",
    "brand.sub": "Plants & Flowers · Castelló · Since 1992",
    "brand.subShort": "Plants & Flowers",
    "footer.tagline": "Plants, flowers and bouquets in Castelló de la Plana since 1992.",
    "footer.shop": "Shop",
    "footer.info": "Information",
    "footer.find": "Find us",
    "footer.copy": "All rights reserved.",
    "auth.signin": "Sign in",
    "auth.signup": "Create account",
    "auth.login.title": "Welcome back",
    "auth.login.sub": "Sign in to your account to manage your orders.",
    "auth.register.title": "Create your account",
    "auth.register.sub": "Save your orders and speed up checkout next time.",
    "auth.aside.title": "Your garden, one click away.",
    "auth.aside.text": "Create an account to save your addresses, orders and favourite plants.",
    "auth.name": "Full name",
    "auth.password": "Password",
    "auth.password.confirm": "Confirm password",
    "auth.alt.toregister": "Don't have an account yet?",
    "auth.alt.tologin": "Already have an account?",
    "auth.alt.toregister.cta": "Create account",
    "auth.alt.tologin.cta": "Sign in",
    "auth.err.missing": "Please fill in all required fields.",
    "auth.err.short": "The password must be at least 6 characters.",
    "auth.err.mismatch": "The passwords don't match.",
    "auth.err.exists": "An account with this email already exists.",
    "auth.err.nouser": "We couldn't find an account with this email.",
    "auth.err.badpass": "The password is incorrect.",
    "auth.err.confirm": "We've sent you an email to confirm your account. Please check your inbox.",
    "auth.err.unknown": "Something went wrong. Please try again.",
    "account.title": "My account",
    "account.welcome": "Hi",
    "account.menu.profile": "Profile",
    "account.menu.orders": "My orders",
    "account.menu.favs": "Favourites",
    "account.menu.cart": "My cart",
    "account.menu.logout": "Log out",
    "account.menu.delete": "Delete account",
    "account.cart.title": "Your current cart",
    "account.cart.sub": "What's in your cart right now.",
    "account.cart.view": "View cart",
    "account.profile.title": "Your details",
    "account.profile.sub": "Keep your information up to date. Only you can see this.",
    "account.profile.emailHint": "For security, the email can't be changed here.",
    "account.profile.save": "Save changes",
    "account.profile.saved": "Saved",
    "account.orders.title": "My orders",
    "account.orders.sub": "All your orders, recent and older.",
    "account.orders.empty": "You haven't placed any orders yet.",
    "account.favs.title": "Saved products",
    "account.favs.empty": "You haven't saved any products yet. Tap the heart on any product to add it here.",
    "account.member": "Customer since",
    "order.status.pending": "Pending",
    "order.status.confirmed": "Confirmed",
    "order.status.paid": "Paid",
    "order.status.shipped": "Shipped",
    "order.status.delivered": "Delivered",
    "order.status.cancelled": "Cancelled",
    "product.origin": "Origin",
    "product.like": "Save",
    "product.liked": "Saved",
    "product.choosePot": "Choose your pot",
    "product.noPot": "No pot",
    "product.free": "Free",
    "likes.toast.title": "Saved to favourites",
    "likes.toast.text": "Create an account to keep your favourites across all your devices.",
    "likes.toast.cta": "Create account",
    "jobs.title": "Work with us",
    "jobs.hero.eyebrow": "Join the team",
    "jobs.hero.title": "<em>Work</em> with us",
    "jobs.hero.lead": "We grow plants, relationships and a team that enjoys what it does.",
    "jobs.card.tag": "Open position",
    "jobs.card.title": "Nursery &amp; florist <em>assistant</em>",
    "jobs.card.meta.location": "📍 Castelló de la Plana",
    "jobs.card.meta.hours": "⏱ Full-time",
    "jobs.card.meta.start": "📅 Immediate start",
    "jobs.duties.heading": "What you'll do",
    "jobs.duties.item1": "Serve customers in the nursery and florist, advising on plants, substrates and care.",
    "jobs.duties.item2": "Prepare and maintain products in the sales area (plants, pots, substrates, decoration).",
    "jobs.duties.item3": "Put together bouquets, centrepieces and simple arrangements for individuals and events.",
    "jobs.duties.item4": "Help with nursery maintenance tasks: watering, repotting, stock control.",
    "jobs.duties.item5": "Occasionally assist with local deliveries and set-ups for customers.",
    "jobs.seek.heading": "What we're looking for",
    "jobs.seek.item1": "A passion for plants and for dealing with people.",
    "jobs.seek.item2": "Availability for split shifts, some full Saturdays and occasional Sundays (special holidays such as Valentine's Day, Mother's Day, All Saints' Day).",
    "jobs.seek.item3": "Spanish and, preferably, Valencian to communicate with local customers.",
    "jobs.seek.item4": "Previous experience isn't essential — we train anyone with drive and the right attitude.",
    "jobs.offer.heading": "What we offer",
    "jobs.offer.item1": "A family team, a well-kept environment, hands-on training.",
    "jobs.offer.item2": "Permanent contract after a trial period.",
    "jobs.offer.item3": "Discounts on plants and products.",
    "jobs.offer.item4": "Castelló de la Plana — no long commutes, 5 min from the centre.",
    "jobs.apply.cta": "Apply for this position",
    "jobs.apply.spont": "Or send a speculative application",
    "jobs.refer": "Not for you but you know someone? Share it — thank you 🌿",
    "jobs.backToOffer": "← Back to the offer",
    "jobs.apply.title": "<em>Your</em> application",
    "jobs.apply.lead": "Just a few steps. Your answers travel encrypted and only we read them.",
    "jobs.stepper.contact": "Contact",
    "jobs.stepper.cv": "CV",
    "jobs.stepper.about": "About you",
    "jobs.step1.note": "We only need your email and phone to get back to you.",
    "jobs.cvStep.title": "Your CV",
    "jobs.cvStep.note": "If you have a CV, upload it. If not, you can continue too — we'll ask you a few questions to get to know you.",
    "jobs.noCv.small": "We'll ask you a few questions",
    "jobs.cvPick": "Choose PDF file…",
    "jobs.cvSelectedLbl": "CV selected:",
    "jobs.privacyLine": "By submitting you accept our <a href=\"privacidad.html\">Privacy Policy</a>.",
    "jobs.success.home": "Back to home",
    "jobs.subtitle": "Join a family team that's grown with care since 1992.",
    "jobs.intro": "If you love plants and dealing with customers, we'd like to meet you. Send us your application — with or without a CV.",
    "jobs.step": "Step",
    "jobs.of": "of",
    "jobs.step1.title": "Your contact details",
    "jobs.step2.title": "Your application",
    "jobs.step2.withCv": "Upload CV (PDF)",
    "jobs.step2.withoutCv": "Continue without CV",
    "jobs.step2.note": "If you don't have a CV ready, that's fine — we'll ask you a few questions to get to know you.",
    "jobs.step3.title": "Tell us a bit more",
    "jobs.step3.optional": "Message (optional)",
    "jobs.step3.optionalPh": "Anything you'd like to share with us…",
    "jobs.back": "Back",
    "jobs.next": "Continue",
    "jobs.submit": "Send application",
    "jobs.success.title": "Application received!",
    "jobs.success.text": "Thank you for your interest. We've saved it and will contact you soon.",
    "jobs.success.ref": "Reference",
    "jobs.privacy": "By submitting you accept our",
    "jobs.cvLimit": "PDF, up to 3 MB",
    "jobs.cvSelected": "CV selected",
    "jobs.cvRemove": "Remove",
    "jobs.required": "Required",
    "jobs.choose": "Select an option"
  },
  va: {
    "nav.home": "Inici",
    "nav.shop": "Botiga",
    "nav.vivero": "Viver",
    "nav.floristeria": "Floristeria",
    "nav.plantas": "Plantes",
    "nav.flores": "Flors",
    "nav.decoracion": "Decoració",
    "nav.eventos": "Esdeveniments",
    "nav.seeAll": "Veure tot",
    "nav.about": "Sobre nosaltres",
    "nav.contact": "Contacte",
    "world.vivero": "Viver & Jardí",
    "world.floristeria": "Floristeria & Flors",
    "world.viveroTag": "Plantes, arbres i tot per al teu jardí",
    "world.floristeriaTag": "Rams, flors i encàrrecs especials",
    "shop.occasions.title": "Ocasions especials",
    "shop.occasions.text": "Casaments, esdeveniments i funerals: flors i decoració per encàrrec.",
    "shop.occasions.cta": "Demanar assessorament",
    "nav.cart": "Cistella",
    "common.viewMore": "Veure més",
    "common.buy": "Comprar",
    "common.addToCart": "Afegir a la cistella",
    "common.added": "Afegit a la cistella",
    "common.favorite": "Afegir a favorits",
    "common.outOfStock": "Sense estoc",
    "favs.title": "Els teus favorits",
    "favs.sub": "Els productes que has guardat per a més tard.",
    "favs.empty.title": "Encara no tens favorits",
    "favs.empty.text": "Toca el cor en qualsevol producte per guardar-lo ací.",
    "favs.empty.cta": "Explorar la botiga",
    "nav.favs": "Favorits",
    "common.inStock": "En estoc",
    "common.units": "unitats",
    "common.price": "Preu",
    "common.quantity": "Quantitat",
    "common.subtotal": "Subtotal",
    "common.total": "Total",
    "common.continue": "Seguir comprant",
    "common.checkout": "Tramitar comanda",
    "common.remove": "Eliminar",
    "common.back": "Tornar",
    "common.send": "Enviar",
    "common.filter": "Filtrar",
    "common.all": "Tots",
    "filter.price": "Preu",
    "filter.from": "Des de",
    "filter.to": "Fins a",
    "filter.type": "Tipus",
    "filter.flowerType": "Tipus de flor",
    "filter.color": "Color",
    "common.search": "Cercar productes…",
    "header.favorites": "Preferits",
    "header.cart": "Cistella",
    "search.recent": "Cerques recents",
    "search.products": "Productes",
    "search.categories": "Categories",
    "search.none": "Sense resultats. Prova una altra paraula.",
    "search.seeAll": "Veure tot per a",
    "common.openMaps": "Obrir en Google Maps",
    "common.callUs": "Crida'ns",
    "common.email": "Escriu-nos",
    "common.hours": "Horari",
    "common.address": "Adreça",
    "common.phone": "Telèfon",
    "common.related": "També et pot interessar",
    "home.hero.eyebrow": "Plantes & Flors · Castelló · 1992",
    "home.hero.title": "<em>Plantes</em> per a casa teua,<br><em>flors</em> per al teu dia.",
    "home.hero.lead": "Viver i floristeria al cor de Castelló de la Plana. Testos, rams, flors de temporada i la planta perfecta per a cada racó.",
    "home.hero.subtitle": "Plantes, arbres, substrats i flors de temporada. Cultivem amb cura des de 1992.",
    "home.hero.cta": "Veure la botiga",
    "home.featured": "Destacats",
    "home.categories": "Categories",
    "home.promise": "<em>Verd</em> per a casa teua.<br><em>Flors</em> per als teus moments.",
    "home.search.go": "Cercar",
    "home.shop.eyebrow": "La botiga",
    "home.shop.title": "Compra ara",
    "home.shop.all": "Veure tota la botiga",
    "home.shop.empty": "Aviat més productes per ací.",
    "home.dept.all": "Tot",
    "home.dept.vivero": "Plantes & Jardí",
    "home.dept.floristeria": "Flors & Esdeveniments",
    "home.depts.eyebrow": "Dues cases, una botiga",
    "home.depts.title": "Què busques hui?",
    "home.shopcat.title": "Compra per categoria",
    "home.depts.viveroSub": "Interior, exterior, arbres, testos i substrats",
    "home.depts.floresSub": "Rams, flors de temporada, casaments i esdeveniments",
    "home.trust.delivery": "Lliurament a Castelló (7 km)",
    "home.trust.pickup": "Recollida a la botiga",
    "home.trust.secure": "Pagament segur",
    "home.trust.since": "Floristeria des de 1992",
    "home.events.eyebrow": "Per al teu esdeveniment",
    "home.events.title": "<em>Flors</em> que conten<br>la teua història",
    "home.events.text": "Casaments, celebracions, homenatges i empreses. T'assessorem sense compromís.",
    "home.events.cta": "Demana pressupost",
    "home.featured.heading": "<em>Una selecció</em><br>del mes",
    "home.story.heading": "<em>Tres dècades</em><br>cuidant plantes",
    "home.story.quote": "«Cada planta porta la mateixa cura que la primera de 1992.»",
    "home.visit.heading": "<em>Vine a vore'ns</em><br>al viver",
    "about.h1": "<em>Tres dècades</em> cultivant",
    "about.h2.story": "<em>Des de 1992,</em><br>un projecte familiar",
    "about.h2.visit": "<em>Vine a vore'ns</em><br>al viver",
    "contact.h1": "<em>Parlem</em>",
    "contact.h2.location": "<em>Castelló</em><br>de la Plana",
    "auth.google.signin": "Continuar amb Google",
    "auth.google.signup": "Registrar-se amb Google",
    "auth.or.email": "o amb el teu correu",
    "home.stats.years": "Anys cultivant",
    "home.stats.species": "Varietats en estoc",
    "home.stats.founded": "Projecte familiar",
    "home.stats.region": "Castelló de la Plana",
    "home.story.title": "La nostra història",
    "home.story.text": "Jazmín naix en 1992 com un projecte familiar: un viver i una floristeria a Castelló. Tres dècades després seguim cuidant cada planta i component cada ram com el primer dia.",
    "home.story.cta": "Conèixer més",
    "home.visit.title": "Visita'ns al viver",
    "home.visit.text": "Passa per les nostres instal·lacions a Castelló de la Plana. T'assessorem sobre la planta perfecta per a cada espai.",
    "shop.title": "La nostra botiga",
    "shop.subtitle": "Més de 40 productes seleccionats. Arreplega a la botiga o sol·licita l'enviament.",
    "shop.empty": "No hi ha productes per a esta selecció.",
    "cart.title": "La teua cistella",
    "cart.empty": "La teua cistella està buida.",
    "cart.emptyCta": "Anar a la botiga",
    "cart.total": "Total",
    "cart.checkout": "Tramitar comanda",
    "checkout.title": "Tramitar comanda",
    "checkout.details": "Dades de contacte",
    "checkout.name": "Nom complet",
    "checkout.emailLbl": "Correu electrònic",
    "checkout.phoneLbl": "Telèfon",
    "checkout.delivery": "Arreplegada / Enviament",
    "checkout.pickup": "Arreplegar a la botiga (gratis)",
    "checkout.ship": "Enviament a domicili",
    "checkout.address": "Adreça d'enviament",
    "checkout.freeShipTag": "Gratis des de 40 €",
    "checkout.cpTown": "Codi postal o població",
    "checkout.locPlaceholder": "Escriu el teu CP o població: 12005, Almassora…",
    "checkout.street": "Carrer i número",
    "checkout.streetPlaceholder": "p. ex. Carrer Major 12, 3rA",
    "checkout.minNotice": "L'enviament a domicili està disponible per a comandes des de 40 €.",
    "checkout.youNeed": "Et falten",
    "checkout.forFreeShip": "per a poder demanar amb enviament.",
    "checkout.inZone": "Repartim a la teua zona!",
    "checkout.outZone": "Esta adreça està fora de la nostra zona de repartiment (7 km). Tria arreplegada a la botiga o escriu-nos.",
    "checkout.notes": "Notes per a la comanda",
    "checkout.summary": "Resum de la comanda",
    "checkout.submit": "Enviar comanda",
    "checkout.success.title": "Comanda rebuda!",
    "checkout.success.text": "Gràcies per confiar en Viveros Jazmín. Ens posarem en contacte amb tu en menys de 24 hores per confirmar la teua comanda.",
    "checkout.success.ref": "Referència",
    "checkout.success.back": "Tornar a l'inici",
    "about.title": "Sobre Jazmín",
    "about.p1": "Viveros Jazmín naix l'any 1992, moment en què una jove parella, ambdós treballadors del sector ornamental, contrauen matrimoni i decideixen emprendre l'aventura de crear un projecte que els permeta treballar junts posant en pràctica tots els coneixements adquirits fins llavors.",
    "about.p2": "Obrin una xicoteta floristeria i comencen a cultivar plantes en un terreny propietat de la família situat a la Cuadra de Los Cubos. Anys més tard la floristeria es trasllada a un local molt més ampli i el viver amplia la seua oferta de varietats.",
    "about.p3": "Actualment, tot l'equip que compon l'empresa treballa amb esforç i il·lusió per a poder oferir, tant a professionals com a aficionats de la jardineria i floristeria, gran varietat de productes.",
    "about.p4": "Al llarg d'estos anys hem creat vincles afectius amb els nostres clients amb qui compartim moments molt agradables. Gràcies a ells i a les seues experiències i coneixements sobre les plantes continuem aprenent cada dia.",
    "contact.title": "Contacte",
    "contact.subtitle": "Tens una pregunta o un encàrrec especial? Estarem encantats d'ajudar-te.",
    "contact.form.name": "El teu nom",
    "contact.form.email": "El teu correu",
    "contact.form.message": "Missatge",
    "contact.form.submit": "Enviar missatge",
    "contact.form.success": "Gràcies! Et respondrem com més prompte millor.",
    "contact.form.phone": "El teu telèfon (opcional)",
    "contact.form.type": "En què podem ajudar-te?",
    "contact.consult": "Prepares un casament, un esdeveniment o un comiat? Componem rams, centres i decoració floral per encàrrec. Conta'ns què necessites i t'assessorem sense compromís.",
    "contact.type.general": "Consulta general",
    "contact.type.boda": "Casament",
    "contact.type.evento": "Esdeveniment o celebració",
    "contact.type.funeral": "Funeral / dol",
    "contact.type.empresa": "Empresa / negoci",
    "contact.type.otro": "Altres",
    "brand.sub": "Plantes & Flors · Castelló · Des de 1992",
    "brand.subShort": "Plantes & Flors",
    "footer.tagline": "Plantes, flors i rams a Castelló de la Plana des de 1992.",
    "footer.shop": "Botiga",
    "footer.info": "Informació",
    "footer.find": "Troba'ns",
    "footer.copy": "Tots els drets reservats.",
    "auth.signin": "Entrar",
    "auth.signup": "Crear compte",
    "auth.login.title": "Benvingut de nou",
    "auth.login.sub": "Accedeix al teu compte per gestionar les teues comandes.",
    "auth.register.title": "Crea el teu compte",
    "auth.register.sub": "Desa les teues comandes i agilita la compra la pròxima vegada.",
    "auth.aside.title": "El teu jardí, a un clic.",
    "auth.aside.text": "Crea un compte per guardar les teues adreces, comandes i plantes preferides.",
    "auth.name": "Nom complet",
    "auth.password": "Contrasenya",
    "auth.password.confirm": "Confirmar contrasenya",
    "auth.alt.toregister": "Encara no tens compte?",
    "auth.alt.tologin": "Ja tens compte?",
    "auth.alt.toregister.cta": "Crear compte",
    "auth.alt.tologin.cta": "Entrar",
    "auth.err.missing": "Si us plau, ompli tots els camps obligatoris.",
    "auth.err.short": "La contrasenya ha de tindre almenys 6 caràcters.",
    "auth.err.mismatch": "Les contrasenyes no coincideixen.",
    "auth.err.exists": "Ja existeix un compte amb este correu.",
    "auth.err.nouser": "No hem trobat un compte amb este correu.",
    "auth.err.badpass": "La contrasenya no és correcta.",
    "auth.err.confirm": "T'hem enviat un correu per a confirmar el teu compte. Revisa la safata d'entrada.",
    "auth.err.unknown": "Alguna cosa ha fallat. Torna-ho a provar.",
    "account.title": "El meu compte",
    "account.welcome": "Hola",
    "account.menu.profile": "Perfil",
    "account.menu.orders": "Les meues comandes",
    "account.menu.favs": "Favorits",
    "account.menu.cart": "La meua cistella",
    "account.menu.logout": "Tancar sessió",
    "account.menu.delete": "Eliminar compte",
    "account.cart.title": "La teua cistella actual",
    "account.cart.sub": "El que tens a la cistella ara mateix.",
    "account.cart.view": "Veure cistella",
    "account.profile.title": "Les teues dades",
    "account.profile.sub": "Manté la teua informació al dia. Només tu pots vore estes dades.",
    "account.profile.emailHint": "Per seguretat, el correu no es pot canviar des d'ací.",
    "account.profile.save": "Guardar canvis",
    "account.profile.saved": "Guardat",
    "account.orders.title": "Les meues comandes",
    "account.orders.sub": "Totes les teues comandes, recents i antigues.",
    "account.orders.empty": "Encara no has fet cap comanda.",
    "account.favs.title": "Productes guardats",
    "account.favs.empty": "Encara no has guardat cap producte. Toca el cor en qualsevol fitxa per afegir-lo ací.",
    "order.status.pending":   "Pendent",
    "order.status.confirmed": "Confirmada",
    "order.status.paid":      "Pagada",
    "order.status.shipped":   "Enviada",
    "order.status.delivered": "Entregada",
    "order.status.cancelled": "Cancel·lada",
    "product.origin": "Origen",
    "product.like": "Guardar",
    "product.liked": "Guardat",
    "product.choosePot": "Tria el teu test",
    "product.noPot": "Sense test",
    "product.free": "Gratis",
    "likes.toast.title": "Guardat als favorits",
    "likes.toast.text": "Crea un compte per conservar els teus favorits en tots els dispositius.",
    "likes.toast.cta": "Crear compte",
    "account.member": "Client des de",
    "jobs.title": "Treballa amb nosaltres",
    "jobs.hero.eyebrow": "Uneix-te a l'equip",
    "jobs.hero.title": "<em>Treballa</em> amb nosaltres",
    "jobs.hero.lead": "Cultivem plantes, relacions i un equip que gaudeix del que fa.",
    "jobs.card.tag": "Plaça oberta",
    "jobs.card.title": "<em>Auxiliar</em> de viver i floristeria",
    "jobs.card.meta.location": "📍 Castelló de la Plana",
    "jobs.card.meta.hours": "⏱ Jornada completa",
    "jobs.card.meta.start": "📅 Incorporació immediata",
    "jobs.duties.heading": "Què faràs",
    "jobs.duties.item1": "Atendre la clientela al viver i la floristeria, assessorant sobre plantes, substrats i cures.",
    "jobs.duties.item2": "Preparar i mantindre els productes a la zona de venda (plantes, cossiols, substrats, decoració).",
    "jobs.duties.item3": "Compondre rams, centres i arranjaments senzills per a particulars i esdeveniments.",
    "jobs.duties.item4": "Donar suport en tasques de manteniment del viver: reg, trasplantaments, control d'estoc.",
    "jobs.duties.item5": "Col·laborar puntualment en lliuraments locals i muntatges per a la clientela.",
    "jobs.seek.heading": "El que busquem",
    "jobs.seek.item1": "Passió per les plantes i pel tracte amb les persones.",
    "jobs.seek.item2": "Disponibilitat per a horari partit, alguns dissabtes complets i diumenges puntuals (festius especials com Sant Valentí, el Dia de la Mare, Tots Sants).",
    "jobs.seek.item3": "Castellà i, preferiblement, valencià per a comunicar-te amb la clientela local.",
    "jobs.seek.item4": "No és imprescindible experiència prèvia — formem qui tinga ganes i actitud.",
    "jobs.offer.heading": "El que oferim",
    "jobs.offer.item1": "Equip familiar, ambient cuidat, formació pràctica.",
    "jobs.offer.item2": "Contracte indefinit després del període de prova.",
    "jobs.offer.item3": "Descomptes en planta i producte.",
    "jobs.offer.item4": "Castelló de la Plana — sense desplaçaments llargs, a 5 min del centre.",
    "jobs.apply.cta": "Aplicar a esta plaça",
    "jobs.apply.spont": "O envia una candidatura espontània",
    "jobs.refer": "No és per a tu però coneixes algú? Comparteix-ho — gràcies 🌿",
    "jobs.backToOffer": "← Tornar a l'oferta",
    "jobs.apply.title": "La <em>teua</em> candidatura",
    "jobs.apply.lead": "Només uns pocs passos. Les teues respostes viatgen xifrades i només les llegim nosaltres.",
    "jobs.stepper.contact": "Contacte",
    "jobs.stepper.cv": "CV",
    "jobs.stepper.about": "Sobre tu",
    "jobs.step1.note": "Només necessitem el correu i el telèfon per a respondre't.",
    "jobs.cvStep.title": "El teu CV",
    "jobs.cvStep.note": "Si tens un CV, puja'l. Si no, també pots continuar — et farem algunes preguntes per a conèixer-te.",
    "jobs.noCv.small": "Et farem unes preguntes",
    "jobs.cvPick": "Triar arxiu PDF…",
    "jobs.cvSelectedLbl": "CV seleccionat:",
    "jobs.privacyLine": "En enviar acceptes la nostra <a href=\"privacidad.html\">Política de Privacitat</a>.",
    "jobs.success.home": "Tornar a l'inici",
    "jobs.subtitle": "Uneix-te a un equip familiar que cultiva amb cura des de 1992.",
    "jobs.intro": "Si t'apassionen les plantes i el tracte amb la clientela, volem conèixer-te. Envia'ns la teua candidatura — amb o sense CV.",
    "jobs.step": "Pas",
    "jobs.of": "de",
    "jobs.step1.title": "Les teues dades de contacte",
    "jobs.step2.title": "La teua candidatura",
    "jobs.step2.withCv": "Pujar CV (PDF)",
    "jobs.step2.withoutCv": "Continuar sense CV",
    "jobs.step2.note": "Si no tens CV preparat, no passa res — et farem unes preguntes per conèixer-te.",
    "jobs.step3.title": "Conta'ns una mica més",
    "jobs.step3.optional": "Missatge (opcional)",
    "jobs.step3.optionalPh": "Qualsevol cosa que vulgues compartir amb nosaltres…",
    "jobs.back": "Enrere",
    "jobs.next": "Continuar",
    "jobs.submit": "Enviar candidatura",
    "jobs.success.title": "Candidatura rebuda!",
    "jobs.success.text": "Gràcies pel teu interès. L'hem guardada i et contactarem prompte.",
    "jobs.success.ref": "Referència",
    "jobs.privacy": "En enviar acceptes la nostra",
    "jobs.cvLimit": "PDF, fins a 3 MB",
    "jobs.cvSelected": "CV seleccionat",
    "jobs.cvRemove": "Llevar",
    "jobs.required": "Obligatori",
    "jobs.choose": "Selecciona una opció"
  }
};
